[package]
name = "chat-spike"
version = "0.1.1"
edition = "2024"

[dependencies]
statrs = "0.18.0"

[dev-dependencies]
anyhow = "^1"
serde_json = "^1"
serde = { version = "^1", features = ["derive"] }
chrono = { version = "*", features = ["serde"] }
